# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokill < Formula
  desc "Interactive process killer for Linux, macOS, and Windows."
  homepage "https://github.com/w31r4/gokill"
  version "1.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/w31r4/gokill/releases/download/v1.2.8/gokill_Darwin_x86_64.tar.gz"
      sha256 "00a3885e32cf097c868bb6afe551d31489e70081aaa8a8959fd8614f0d54ba0f"

      def install
        bin.install "gokill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/w31r4/gokill/releases/download/v1.2.8/gokill_Darwin_arm64.tar.gz"
      sha256 "52b92ec4cb93076299cad887438bf769e52c06c1b722d783486890e2f18e72aa"

      def install
        bin.install "gokill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/w31r4/gokill/releases/download/v1.2.8/gokill_Linux_x86_64.tar.gz"
      sha256 "4c7a788a3f0f83693976c23162beefade297449970f4ef3bcf0db7b998095a50"
      def install
        bin.install "gokill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/w31r4/gokill/releases/download/v1.2.8/gokill_Linux_arm64.tar.gz"
      sha256 "ea67aa8da725644d4deab7c72bd65883783bc5b901a3b17e9fcae2c219b0165a"
      def install
        bin.install "gokill"
      end
    end
  end
end
