# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gokill < Formula
  desc "Interactive process killer for Linux and macOS."
  homepage "https://github.com/w31r4/gokill"
  version "1.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/w31r4/gokill/releases/download/v1.4.1/gokill_Darwin_x86_64.tar.gz"
      sha256 "84553f010b98480d320abe59ff98927fa66bb5848085626c8190085796de6702"

      def install
        bin.install "gokill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/w31r4/gokill/releases/download/v1.4.1/gokill_Darwin_arm64.tar.gz"
      sha256 "0068343c28ae040412f082f12d115d5bad5bc64d446c5e2e9cd6f2d0113c6415"

      def install
        bin.install "gokill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/w31r4/gokill/releases/download/v1.4.1/gokill_Linux_x86_64.tar.gz"
      sha256 "efad865d2e0b6207c5f10d548f2e332f1ebf34ce282e5cd39e26afc697ff0f0f"
      def install
        bin.install "gokill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/w31r4/gokill/releases/download/v1.4.1/gokill_Linux_arm64.tar.gz"
      sha256 "0a1ee43da068ca40555bb4273c993f4286f9705cf86b4e644a5d5d66b8e1109d"
      def install
        bin.install "gokill"
      end
    end
  end
end
